name: Update maplibre-native dependency

on:
  schedule:
    # The first day of every month at 12:00 AM UTC
    - cron: "0 12 1 * *"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update-dependency:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with: { persist-credentials: false }
      - name: Install just
        uses: taiki-e/install-action@f79fe7514db78f0a7bdba3cb6dd9c1baa7d046d9 # v2.62.56
        with:
          tool: just

      - name: Update maplibre-native
        run: just update-maplibre-native

      - name: Get maplibre-native details
        id: maplibre-details
        run: |
          echo "details<<EOF" >> $GITHUB_OUTPUT
          just show-maplibre-native
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@84ae59a2cdc2258d6fa0732dd66352dddae2a412 # v7.0.9
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: update `maplibre-native`"
          title: "chore(deps): update `maplibre-native`"
          body: |
            ## Automated `maplibre-native` dependency update

            This PR updates `package.metadata.mln.release` in `Cargo.toml` to the latest Maplibre Native Core release.

            ${{ steps.maplibre-details.outputs.details }}
          branch: update-maplibre-native-dependency
          delete-branch: true
          labels: dependencies
