name: Update maplibre-native dependency

on:
  schedule:
    # The first day of every month at 12:00 AM UTC
    - cron: "0 12 1 * *"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update-dependency:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with: { persist-credentials: false }
      - name: Install just
        uses: taiki-e/install-action@81a2f66614862089b24532663f669a485d79c889 # v2.67.10
        with:
          tool: just

      - name: Update maplibre-native
        run: just update-maplibre-native

      - name: Get maplibre-native details
        id: maplibre-details
        run: |
          echo "details<<EOF" >> $GITHUB_OUTPUT
          just show-maplibre-native
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@c0f553fe549906ede9cf27b5156039d195d2ece0 # v8.1.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: update `maplibre-native`"
          title: "chore(deps): update `maplibre-native`"
          body: |
            ## Automated `maplibre-native` dependency update

            This PR updates `package.metadata.mln.release` in `Cargo.toml` to the latest Maplibre Native Core release.

            ${{ steps.maplibre-details.outputs.details }}
          branch: update-maplibre-native-dependency
          delete-branch: true
          labels: dependencies
